(function accessControl(){
  if(typeof document==='undefined')return;
  const PAYMENT_URL='https://www.asaas.com/000/c/f26ysln4a6j8ndns';
  const root=document.createElement('section');root.className='access-panel';root.innerHTML='<div class="access-card"><img class="access-logo" src="logo-mapavoto.png" alt="Mapa do Voto"><p class="eyebrow">ACESSO AO MAPA DO VOTO</p><h2 id="accessTitle">Entre ou crie sua conta</h2><p id="accessMessage">O acesso inicial é válido por 24 horas.</p><div id="accessTimer" class="access-timer" hidden></div><form id="accessForm"><input name="name" placeholder="Nome" autocomplete="name"><input name="email" type="email" placeholder="E-mail" autocomplete="email" required><input name="password" type="password" placeholder="Senha (mínimo 10 caracteres)" autocomplete="new-password" required><div><button type="submit">Criar acesso</button><button type="button" id="accessLogin">Já tenho login</button></div></form><button id="accessPay" hidden>Renovar por R$ 149,90</button><p id="accessStatus" role="status"></p></div>';document.body.prepend(root);
  const style=document.createElement('style');style.textContent='.access-panel{overflow-y:auto;box-sizing:border-box;min-height:100dvh}.access-card{width:min(100%,576px);max-height:calc(100dvh - 32px);overflow-y:auto;box-sizing:border-box;text-align:center;padding:clamp(22px,5vw,44px);border-radius:clamp(18px,4vw,28px)}.access-logo{display:block;width:clamp(64px,14vw,92px);height:clamp(64px,14vw,92px);object-fit:contain;margin:0 auto clamp(14px,3vw,24px);border-radius:18px}.access-card form{text-align:center}.access-card form>input{width:100%;box-sizing:border-box}.access-card form>div{display:flex;justify-content:center;align-items:center;gap:10px;flex-wrap:wrap}.access-card .eyebrow{margin-bottom:10px}.access-card h2{margin-top:0;font-size:clamp(28px,5vw,42px);line-height:1.08}.access-card p{font-size:clamp(16px,2.4vw,21px)}.access-card button{margin:8px 0 0}.access-card #accessStatus{font-size:14px}@media (max-width:420px){.access-panel{padding:10px}.access-card{max-height:calc(100dvh - 20px);padding:22px 16px}.access-card form>div{display:grid;grid-template-columns:1fr;width:100%}.access-card button{width:100%}}';document.head.appendChild(style);
  const form=root.querySelector('#accessForm'),status=root.querySelector('#accessStatus'),timer=root.querySelector('#accessTimer'),pay=root.querySelector('#accessPay'),title=root.querySelector('#accessTitle'),message=root.querySelector('#accessMessage');
  let login=false;
  const api=(url,body)=>fetch(url,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify(body)}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Não foi possível concluir');return data});
  const localKey='mapa_do_voto_local_user';
  const localHash=async value=>{const bytes=new TextEncoder().encode(value),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')};
  const localAccess=async data=>{if(data.password.length<10)throw new Error('A senha deve ter no mínimo 10 caracteres.');const saved=JSON.parse(localStorage.getItem(localKey)||'null');if(login){if(!saved||saved.email!==data.email.trim().toLowerCase()||saved.passwordHash!==await localHash(data.password))throw new Error('E-mail ou senha inválidos.');}else{if(saved&&saved.email===data.email.trim().toLowerCase())throw new Error('Este e-mail já está cadastrado neste navegador.');localStorage.setItem(localKey,JSON.stringify({name:data.name.trim(),email:data.email.trim().toLowerCase(),passwordHash:await localHash(data.password),expiresAt:Date.now()+86400000}));}return{access:{expiresAt:(JSON.parse(localStorage.getItem(localKey))).expiresAt}}};
  const showTimer=expires=>{timer.hidden=false;const tick=()=>{const left=Math.max(0,new Date(expires)-Date.now());if(!left){timer.textContent='Acesso expirado';pay.hidden=false;return}const h=Math.floor(left/3600000),m=Math.floor(left%3600000/60000),s=Math.floor(left%60000/1000);timer.textContent=`Acesso disponível por ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;setTimeout(tick,1000)};tick()};
  const render=async()=>{try{const r=await fetch('/api/auth/me',{credentials:'include'});const data=await r.json();if(!r.ok)throw new Error();root.hidden=true;document.body.classList.remove('access-locked');if(!data.access){root.hidden=false;title.textContent='Período de acesso encerrado';message.textContent='Renove o acesso para utilizar o sistema por mais 365 dias.';form.hidden=true;pay.hidden=false;document.body.classList.add('access-locked')}else if(data.user?.accessExpiresAt)showTimer(data.user.accessExpiresAt)}catch{root.hidden=false;document.body.classList.add('access-locked')}};
  form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));try{status.textContent=login?'Entrando…':'Criando conta…';const result=await api(login?'/api/auth/login':'/api/auth/register',data);status.textContent='Acesso autorizado.';if(result.access?.expiresAt)showTimer(result.access.expiresAt);await render()}catch(error){try{const result=await localAccess(data);root.hidden=true;document.body.classList.remove('access-locked');status.textContent='Modo local temporário ativo.';showTimer(result.access.expiresAt)}catch(localError){status.textContent=localError.message}}};
  root.querySelector('#accessLogin').onclick=()=>{login=!login;const nameField=form.querySelector('input[name="name"]');nameField.hidden=login;nameField.required=!login;root.querySelector('#accessLogin').textContent=login?'Criar conta':'Já tenho login';title.textContent=login?'Entrar no sistema':'Entre ou crie sua conta'};
  pay.onclick=()=>{window.open(PAYMENT_URL,'_blank','noopener,noreferrer')};render();
}());
