(function accessControl(){
  if(typeof document==='undefined')return;
  const PAYMENT_URL='https://www.asaas.com/000/c/f26ysln4a6j8ndns';
  const root=document.createElement('section');root.className='access-panel';root.innerHTML='<div class="access-card"><p class="eyebrow">ACESSO AO MAPA DO VOTO</p><h2 id="accessTitle">Entre ou crie sua conta</h2><p id="accessMessage">O acesso inicial é válido por 24 horas.</p><div id="accessTimer" class="access-timer" hidden></div><form id="accessForm"><input name="name" placeholder="Nome" autocomplete="name"><input name="email" type="email" placeholder="E-mail" autocomplete="email" required><input name="password" type="password" placeholder="Senha (mínimo 10 caracteres)" autocomplete="new-password" required><div><button type="submit">Criar acesso</button><button type="button" id="accessLogin">Já tenho login</button></div></form><button id="accessPay" hidden>Renovar por R$ 149,90</button><p id="accessStatus" role="status"></p></div>';document.body.prepend(root);
  const form=root.querySelector('#accessForm'),status=root.querySelector('#accessStatus'),timer=root.querySelector('#accessTimer'),pay=root.querySelector('#accessPay'),title=root.querySelector('#accessTitle'),message=root.querySelector('#accessMessage');
  let login=false;
  const api=(url,body)=>fetch(url,{method:'POST',headers:{'content-type':'application/json'},credentials:'include',body:JSON.stringify(body)}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Não foi possível concluir');return data});
  const showTimer=expires=>{timer.hidden=false;const tick=()=>{const left=Math.max(0,new Date(expires)-Date.now());if(!left){timer.textContent='Acesso expirado';pay.hidden=false;return}const h=Math.floor(left/3600000),m=Math.floor(left%3600000/60000),s=Math.floor(left%60000/1000);timer.textContent=`Acesso disponível por ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;setTimeout(tick,1000)};tick()};
  const render=async()=>{try{const r=await fetch('/api/auth/me',{credentials:'include'});const data=await r.json();if(!r.ok)throw new Error();root.hidden=true;document.body.classList.remove('access-locked');if(!data.access){root.hidden=false;title.textContent='Período de acesso encerrado';message.textContent='Renove o acesso para utilizar o sistema por mais 365 dias.';form.hidden=true;pay.hidden=false;document.body.classList.add('access-locked')}else if(data.user?.accessExpiresAt)showTimer(data.user.accessExpiresAt)}catch{root.hidden=false;document.body.classList.add('access-locked')}};
  form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));try{status.textContent=login?'Entrando…':'Criando conta…';const result=await api(login?'/api/auth/login':'/api/auth/register',data);status.textContent='Acesso autorizado.';if(result.access?.expiresAt)showTimer(result.access.expiresAt);await render()}catch(error){status.textContent=error.message}};
  root.querySelector('#accessLogin').onclick=()=>{login=!login;const nameField=form.querySelector('input[name="name"]');nameField.hidden=login;nameField.required=!login;root.querySelector('#accessLogin').textContent=login?'Criar conta':'Já tenho login';title.textContent=login?'Entrar no sistema':'Entre ou crie sua conta'};
  pay.onclick=()=>{window.open(PAYMENT_URL,'_blank','noopener,noreferrer')};render();
}());
