(function(){'use strict';const nf=new Intl.NumberFormat('pt-BR');
function calculateChange(a,b){return{absolute:b-a,percent:a===0?null:(b-a)/a*100}}
function filterZones(rows,f){return rows.filter(x=>(f.region==='all'||x.region===f.region)&&(f.municipality==='all'||x.municipality===f.municipality)&&(f.place==='all'||x.id===f.place)&&(f.zone==='all'||String(x.zone)===String(f.zone)))}
function sortZones(rows,sort,currentYear){const copy=[...rows],change=x=>x.difference;if(sort==='growth-desc')return copy.sort((a,b)=>change(b)-change(a));if(sort==='growth-asc')return copy.sort((a,b)=>change(a)-change(b));if(sort==='name-asc')return copy.sort((a,b)=>(a.municipality+a.place).localeCompare(b.municipality+b.place,'pt-BR'));return copy.sort((a,b)=>b.votes[currentYear]-a.votes[currentYear])}
function aggregate(rows,years){return rows.reduce((totals,row)=>{years.forEach(year=>totals[year]+=row.votes[year]);return totals},Object.fromEntries(years.map(year=>[year,0])))}
if(typeof module!=='undefined')module.exports={calculateChange,filterZones,sortZones,aggregate};if(typeof document==='undefined'||!window.ELECTION_DATA)return;
const $=s=>document.querySelector(s),db=window.ELECTION_DATA,els={candidate:$('#candidateFilter'),region:$('#regionFilter'),municipality:$('#municipalityFilter'),place:$('#placeFilter'),zone:$('#zoneFilter'),sort:$('#sortFilter'),chart:$('#chart'),ranking:$('#rankingBody'),highlights:$('#highlights'),a:$('#compareA'),b:$('#compareB')};let chartType='bar';let candidate;
const unique=a=>[...new Set(a)].sort((x,y)=>String(x).localeCompare(String(y),'pt-BR',{numeric:true}));const signed=n=>`${n>=0?'+':'−'}${nf.format(Math.abs(n))}`;const add=(select,values,label=x=>x,value=x=>x)=>values.forEach(x=>select.add(new Option(label(x),value(x))));
function resetSelect(select,label,values,render=x=>x,value=x=>x){const old=select.value;select.replaceChildren(new Option(label,'all'));add(select,values,render,value);if([...select.options].some(option=>option.value===old))select.value=old}
function setCandidate(){candidate=db.candidates[els.candidate.value];const[first,current]=candidate.years.map(String);$('#heroName').textContent=candidate.name.toUpperCase();$('#heroNumber').textContent=candidate.number;$('#sideNumber').textContent=candidate.number;$('#sideName').textContent=`${candidate.name.toUpperCase()} · ${candidate.party}`;$('#heroPeriod').textContent=`COMPARATIVO ${first} × ${current}`;$('#heroOffice').textContent=candidate.offices[current].toUpperCase();$('#firstYearLabel').textContent=`VOTOS EM ${first}`;$('#secondYearLabel').textContent=`VOTOS EM ${current}`;$('#firstOfficeLabel').textContent=candidate.offices[first];$('#secondOfficeLabel').textContent=candidate.offices[current];$('#legendFirst').textContent=`● ${first}`;$('#legendSecond').textContent=`● ${current}`;$('#tableFirst').textContent=first;$('#tableSecond').textContent=current;els.sort.querySelector('option[value="current-desc"]').textContent=`Mais votos em ${current}`;$('#coverageNote').innerHTML=`<b>Cobertura integral:</b> ${nf.format(candidate.audit.sourceRows)} pares município-zona únicos. Votos reconciliados: ${nf.format(candidate.totals[first])} em ${first} e ${nf.format(candidate.totals[current])} em ${current}.${els.candidate.value==='sandra'?' A comparação cruza cargos diferentes: vereadora municipal em 2024 e deputada estadual em 2026.':''}`;populateFilters();populateCompare();render()}
function populateFilters(){resetSelect(els.region,'Todas as regiões',unique(candidate.zones.map(x=>x.region)));resetSelect(els.municipality,'Todos os municípios',unique(candidate.zones.map(x=>x.municipality)));resetSelect(els.place,'Todas as zonas',candidate.zones,x=>`${x.municipality} · ${x.place} · ZE ${x.zone}`,x=>x.id);resetSelect(els.zone,'Todas as ZEs',unique(candidate.zones.map(x=>x.zone)),x=>`ZE ${x}`)}
function populateCompare(){els.a.replaceChildren();els.b.replaceChildren();candidate.zones.forEach(x=>{const label=`${x.municipality} · ${x.place} · ZE ${x.zone}`;els.a.add(new Option(label,x.id));els.b.add(new Option(label,x.id))});els.a.selectedIndex=0;els.b.selectedIndex=Math.min(1,candidate.zones.length-1)}
function dependent(){const base=candidate.zones.filter(x=>(els.region.value==='all'||x.region===els.region.value)&&(els.municipality.value==='all'||x.municipality===els.municipality.value));resetSelect(els.place,'Todas as zonas',base,x=>`${x.municipality} · ${x.place} · ZE ${x.zone}`,x=>x.id);resetSelect(els.zone,'Todas as ZEs',unique(base.map(x=>x.zone)),x=>`ZE ${x}`)}
function visible(){const current=String(candidate.years[1]);return sortZones(filterZones(candidate.zones,{region:els.region.value,municipality:els.municipality.value,place:els.place.value,zone:els.zone.value}),els.sort.value,current)}
function metrics(rows){const years=candidate.years.map(String),full=rows.length===candidate.zones.length,totals=full?candidate.totals:aggregate(rows,years),d=calculateChange(totals[years[0]],totals[years[1]]);$('#votes2022').textContent=nf.format(totals[years[0]]);$('#votes2026').textContent=nf.format(totals[years[1]]);$('#growthValue').textContent=d.percent===null?'Novos votos':`${d.percent>=0?'+':''}${d.percent.toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;$('#growthValue').className=d.absolute>=0?'positive':'negative';$('#growthAbsolute').textContent=`${signed(d.absolute)} votos`;$('#recordsValue').textContent=nf.format(full?candidate.records[years[1]]:rows.length);$('#recordsLabel').textContent=full?`Registros brutos em ${years[1]}`:'Pares município-zona no recorte'}
function chartItems(rows){if(els.region.value==='all'&&els.municipality.value==='all'&&els.place.value==='all'&&els.zone.value==='all')return candidate.regions.slice(0,10).map(x=>({label:x.name,votes:x.votes}));return rows.slice(0,10).map(x=>({label:x.municipality==='SAO PAULO'?x.place:x.municipality,votes:x.votes}))}
function bars(items){const years=candidate.years.map(String),max=Math.max(1,...items.flatMap(x=>years.map(y=>x.votes[y])));els.chart.innerHTML=`<div class="bars">${items.map(x=>`<div class="bar-row"><span title="${x.label}">${x.label}</span><div><i class="bar old" style="width:${x.votes[years[0]]/max*100}%"></i><b>${nf.format(x.votes[years[0]])}</b><i class="bar new" style="width:${x.votes[years[1]]/max*100}%"></i><b>${nf.format(x.votes[years[1]])}</b></div></div>`).join('')}</div>`}
function lines(items){const years=candidate.years.map(String),w=760,h=300,p=45,max=Math.max(1,...items.flatMap(x=>years.map(y=>x.votes[y]))),X=i=>items.length===1?w/2:p+i*(w-p*2)/(items.length-1),Y=v=>h-p-v/max*(h-p*2),points=y=>items.map((x,i)=>`${X(i)},${Y(x.votes[y])}`).join(' ');els.chart.innerHTML=`<div class="line"><svg viewBox="0 0 ${w} ${h}">${[0,.25,.5,.75,1].map(s=>`<line x1="${p}" y1="${Y(max*s)}" x2="${w-p}" y2="${Y(max*s)}"/>`).join('')}<polyline class="old" points="${points(years[0])}"/><polyline class="new" points="${points(years[1])}"/>${items.map((x,i)=>`<circle class="old" cx="${X(i)}" cy="${Y(x.votes[years[0]])}" r="4"/><circle class="new" cx="${X(i)}" cy="${Y(x.votes[years[1]])}" r="4"/><text x="${X(i)}" y="${h-8}" text-anchor="middle">${x.label.slice(0,10)}</text>`).join('')}</svg></div>`}
function highlights(rows){if(!rows.length){els.highlights.innerHTML='<p class="empty">Nenhum resultado.</p>';return}const ranked=[...rows].sort((a,b)=>b.difference-a.difference),current=String(candidate.years[1]),cards=[['↗','MAIOR AVANÇO',ranked[0]],['↘','PONTO DE ATENÇÃO',ranked.at(-1)],['★','MAIOR VOLUME',[...rows].sort((a,b)=>b.votes[current]-a.votes[current])[0]]];els.highlights.innerHTML=cards.map(([icon,label,x])=>`<div class="highlight"><i>${icon}</i><div><small>${label}</small><strong>${x.municipality==='SAO PAULO'?x.place:x.municipality}</strong><p>ZE ${x.zone} · ${signed(x.difference)} votos</p></div></div>`).join('')}
function ranking(rows){const years=candidate.years.map(String);window.__exportRows=rows;window.__exportCandidate=candidate;$('#resultCount').textContent=`${nf.format(rows.length)} resultado${rows.length===1?'':'s'} de ${nf.format(candidate.zones.length)}`;els.ranking.innerHTML=rows.length?rows.map((x,i)=>`<tr><td><i class="rank">${i+1}</i></td><td><b>${x.municipality}</b><br><small>${x.place}</small></td><td>${x.region}</td><td>ZE ${x.zone}</td><td>${nf.format(x.votes[years[0]])}</td><td><b>${nf.format(x.votes[years[1]])}</b></td><td><span class="change ${x.difference>=0?'up':'down'}">${signed(x.difference)}</span></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Nenhum resultado para estes filtros.</td></tr>'}
function comparison(){const years=candidate.years.map(String),left=candidate.zones.find(x=>x.id===els.a.value),right=candidate.zones.find(x=>x.id===els.b.value);window.__comparisonSelection={candidate,years,left,right};const card=(x,m)=>`<article><i>${m}</i><div><small>${x.municipality} · ${x.region} · ZE ${x.zone}</small><h3>${x.place}</h3></div><dl><div><dt>${years[0]}</dt><dd>${nf.format(x.votes[years[0]])}</dd></div><div><dt>${years[1]}</dt><dd>${nf.format(x.votes[years[1]])}</dd></div><div><dt>Variação</dt><dd class="${x.difference>=0?'positive':'negative'}">${signed(x.difference)}</dd></div></dl></article>`;$('#comparisonResult').innerHTML=card(left,'A')+'<b class="vs">VS</b>'+card(right,'B')}
function render(){const rows=visible();metrics(rows);chartType==='bar'?bars(chartItems(rows)):lines(chartItems(rows));highlights(rows);ranking(rows);comparison()}
els.candidate.onchange=setCandidate;[els.region,els.municipality].forEach(s=>s.onchange=()=>{dependent();render()});[els.place,els.zone,els.sort].forEach(s=>s.onchange=render);[els.a,els.b].forEach(s=>s.onchange=comparison);$('#swapCompare').onclick=()=>{[els.a.value,els.b.value]=[els.b.value,els.a.value];comparison()};$('#resetFilters').onclick=()=>{[els.region,els.municipality,els.place,els.zone].forEach(s=>s.value='all');els.sort.value='current-desc';dependent();render()};document.querySelectorAll('[data-chart]').forEach(button=>{button.type='button';button.addEventListener('click',event=>{event.preventDefault();const next=button.dataset.chart;if(next!=='bar'&&next!=='line')return;chartType=next;document.querySelectorAll('[data-chart]').forEach(x=>x.classList.toggle('active',x.dataset.chart===chartType));render()})});$('#menuButton').onclick=e=>{const open=document.body.classList.toggle('menu-open');e.currentTarget.setAttribute('aria-expanded',open)};setCandidate();
}());

(function addCandidateAccessAndUpload(){
  if(typeof document==='undefined'||!window.ELECTION_DATA)return;
  const candidates={andre:{name:'André Bueno',number:'15777',photo:'https://borabueno.com.br/assets/og-image.jpg'},sandra:{name:'Sandra Santana',number:'15456',photo:''}};
  const overlay=document.createElement('div');
  overlay.className='access-gate';
  overlay.innerHTML='<div class="access-card"><div class="access-brand">PAINEL ELEITORAL <span>●</span></div><p class="eyebrow">ACESSO POR CAMPANHA</p><h2>Escolha o candidato</h2><p class="access-copy">Cada acesso libera somente os dados e métricas da campanha selecionada.</p><div class="candidate-access-list"></div><label class="access-password">Senha do candidato<input id="candidatePassword" type="password" inputmode="numeric" autocomplete="off" maxlength="5" placeholder="Número do candidato"></label><button id="accessSubmit" class="access-submit" type="button">Entrar no painel</button><p id="accessMessage" class="access-message" role="alert"></p><small class="access-note">Controle de interface para esta versão estática. Autenticação real exige backend.</small></div>';
  document.body.prepend(overlay);document.body.classList.add('access-locked');
  const list=overlay.querySelector('.candidate-access-list');let selected='andre';
  Object.entries(candidates).forEach(function(entry){const key=entry[0],item=entry[1],button=document.createElement('button');button.type='button';button.className='candidate-access selected';button.dataset.candidate=key;button.innerHTML='<span class="candidate-photo" style="background-image:'+(item.photo?'url('+item.photo+')':'')+'">'+(item.photo?'':'SS')+'</span><span><b>'+item.name+'</b><small>'+item.number+'</small></span>';button.onclick=function(){selected=key;document.querySelectorAll('.candidate-access').forEach(function(x){x.classList.toggle('selected',x===button)})};list.appendChild(button)});
  function enter(){const password=overlay.querySelector('#candidatePassword').value;if(password!==candidates[selected].number){overlay.querySelector('#accessMessage').textContent='Senha inválida para o candidato selecionado.';return}sessionStorage.setItem('candidate_access',selected);overlay.remove();document.body.classList.remove('access-locked');const selector=document.querySelector('#candidateFilter');selector.value=selected;selector.disabled=true;selector.dispatchEvent(new Event('change'))}
  overlay.querySelector('#accessSubmit').onclick=enter;overlay.querySelector('#candidatePassword').onkeydown=function(e){if(e.key==='Enter')enter()};
  const toolbar=document.querySelector('header'),uploadButton=document.createElement('button');uploadButton.type='button';uploadButton.className='upload-action';uploadButton.textContent='Adicionar base';toolbar.appendChild(uploadButton);
  const uploadPanel=document.createElement('div');uploadPanel.className='upload-panel';uploadPanel.innerHTML='<div class="upload-panel-inner"><button class="upload-close" type="button" aria-label="Fechar">×</button><p class="eyebrow">INGESTÃO CONTROLADA</p><h2>Adicionar nova base</h2><p>Envie CSV ou JSON estruturado com município, região, zona, referência territorial, ano e votos. CPF, RG, nome civil e outros identificadores pessoais são bloqueados.</p><div class="upload-schema">Formato recomendado: <code>candidate,year,municipality,region,zone,place,votes</code></div><label class="upload-drop">Selecionar arquivo<input class="upload-input" type="file" accept=".csv,.json"></label><p class="upload-result" role="status"></p></div>';document.body.appendChild(uploadPanel);
  uploadButton.onclick=function(){uploadPanel.classList.add('open')};uploadPanel.querySelector('.upload-close').onclick=function(){uploadPanel.classList.remove('open')};
  const forbidden=/cpf|rg|nome[_ ]?civil|data[_ ]?nascimento|telefone|email|endereco|endereço/i,result=uploadPanel.querySelector('.upload-result');
  uploadPanel.querySelector('.upload-input').onchange=async function(event){const file=event.target.files[0];if(!file)return;const text=await file.text(),firstLine=text.split(/\r?\n/,1)[0];if(forbidden.test(firstLine)){result.textContent='Arquivo rejeitado: contém campo pessoal não permitido.';result.className='upload-result invalid';return}const headers=firstLine.split(/[;,]/).map(function(x){return x.trim().toLowerCase()}),required=['candidate','year','municipality','region','zone','place','votes'],missing=required.filter(function(x){return !headers.includes(x)});if(missing.length){result.textContent='Arquivo rejeitado. Campos ausentes: '+missing.join(', ')+'.';result.className='upload-result invalid';return}const rows=Math.max(0,text.trim().split(/\r?\n/).length-1);localStorage.setItem('last_upload_metadata',JSON.stringify({name:file.name,rows:rows,uploadedAt:new Date().toISOString(),status:'staged'}));result.textContent='Arquivo validado e colocado em quarentena: '+rows.toLocaleString('pt-BR')+' linhas. A base oficial não foi alterada.';result.className='upload-result valid'};
  if(sessionStorage.getItem('candidate_access')){const key=sessionStorage.getItem('candidate_access');const selector=document.querySelector('#candidateFilter');selector.value=key;selector.disabled=true;overlay.remove();document.body.classList.remove('access-locked')}
}());
/* Enforce candidate-scoped visibility for private campaign panels. */
(function enforceCandidateScope(){
  if(typeof document==='undefined')return;
  function applyScope(key){
    if(!key)return;
    const selector=document.querySelector('#candidateFilter');
    if(selector){selector.value=key;selector.disabled=true;selector.closest('label')?.setAttribute('hidden','');}
    document.querySelectorAll('#raw-data .downloads a').forEach(function(link){
      const href=link.getAttribute('href')||'';
      const owner=href.includes('andre_bueno_')?'andre':href.includes('sandra_santana_')?'sandra':null;
      if(owner===null||owner===key)link.hidden=owner!==key?false:link.hidden;
      else link.hidden=true;
    });
    document.querySelectorAll('#raw-data .downloads a[href*="audit"]').forEach(function(link){link.hidden=true;});
    const heading=document.querySelector('#raw-data h2');
    if(heading)heading.textContent=key==='andre'?'Base bruta da campanha de André Bueno':'Base bruta da campanha de Sandra Santana';
  }
  applyScope(sessionStorage.getItem('candidate_access'));
  const scopeTimer=setInterval(function(){const key=sessionStorage.getItem('candidate_access');if(key){applyScope(key);clearInterval(scopeTimer);}},250);
  window.addEventListener('candidate-scope-ready',function(event){applyScope(event.detail);});
}());
/* Explicit search action: the button re-runs the cross-filter query on demand. */
(function addSearchAction(){
  if(typeof document==='undefined')return;
  const territoryCard=document.querySelector('#territories');
  if(!territoryCard||document.querySelector('#searchCombinations'))return;
  const button=document.createElement('button');
  button.id='searchCombinations';
  button.type='button';
  button.className='search-action';
  button.textContent='Cruzar Dados';
  const head=territoryCard.querySelector('.head');
  head.appendChild(button);
  button.addEventListener('click',()=>{
    document.querySelector('#sortFilter')?.dispatchEvent(new Event('change',{bubbles:true}));
    const result=document.querySelector('#resultCount');
    if(result)result.setAttribute('data-search-state','Busca executada');
    window.scrollTo({top:territoryCard.offsetTop-18,behavior:'smooth'});
    document.querySelector('#ranking')?.classList.add('search-complete');
  });
}());
(function addExportActions(){
  if(typeof document==='undefined')return;
  const card=document.querySelector('#ranking');if(!card||document.querySelector('#exportCsv'))return;
  const head=card.querySelector('.head'),tools=document.createElement('div');tools.className='export-actions';
  tools.innerHTML='<button id="exportCsv" type="button">Baixar Excel (CSV)</button><button id="exportTxt" type="button">Baixar TXT</button><button id="exportComparison" type="button">Baixar comparação</button><button id="printQuery" type="button">Imprimir</button>';head.appendChild(tools);
  const download=(name,content,type)=>{const blob=new Blob(['\ufeff'+content],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  const csvValue=value=>`"${String(value??'').replace(/"/g,'""')}"`;
  function report(){const c=window.__exportCandidate,rows=window.__exportRows||[],years=c.years.map(String);return {c,rows,years};}
  document.querySelector('#exportCsv').onclick=()=>{const {c,rows,years}=report();const lines=[['Candidato','Ano inicial','Ano atual','Municipio','Referencia','Regiao','Zona eleitoral','Votos inicial','Votos atual','Variacao'].map(csvValue).join(';'),...rows.map(x=>[c.name,years[0],years[1],x.municipality,x.place,x.region,x.zone,x.votes[years[0]],x.votes[years[1]],x.difference].map(csvValue).join(';'))];download('consulta_eleitoral.csv',lines.join('\r\n'),'text/csv;charset=utf-8')};
  document.querySelector('#exportTxt').onclick=()=>{const {c,rows,years}=report();const text=[`PAINEL ELEITORAL - ${c.name}`,`Consulta: ${new Date().toLocaleString('pt-BR')}`,`Comparacao: ${years[0]} x ${years[1]}`,`Resultados: ${rows.length}`, '',...rows.map((x,i)=>`${i+1}. ${x.municipality} - ${x.place} | Regiao: ${x.region} | ZE: ${x.zone} | ${years[0]}: ${x.votes[years[0]]} | ${years[1]}: ${x.votes[years[1]]} | Variacao: ${x.difference}`)];download('consulta_eleitoral.txt',text.join('\n'),'text/plain;charset=utf-8')};
  document.querySelector('#exportComparison').onclick=()=>{const x=window.__comparisonSelection;if(!x?.left||!x?.right)return;const line=(label,row)=>`${label};${row.municipality};${row.place};${row.region};ZE ${row.zone};${row.votes[x.years[0]]};${row.votes[x.years[1]]};${row.difference}`;download('comparacao_eleitoral.csv',['Tipo;Municipio;Referencia;Regiao;Zona;Votos inicial;Votos atual;Variacao',line('A',x.left),line('B',x.right)].join('\r\n'),'text/csv;charset=utf-8')};
  document.querySelector('#printQuery').onclick=()=>window.print();
}());
(function addCampaignImprovement(){
  if(typeof document==='undefined')return;
  const territory=document.querySelector('#territories'),head=territory?.querySelector('.head');
  if(!head||document.querySelector('#campaignImprove'))return;
  const button=document.createElement('button');button.id='campaignImprove';button.type='button';button.className='search-action';button.textContent='Aperfeiçoar Campanha';head.appendChild(button);
  const panel=document.createElement('div');panel.className='opportunity-panel';panel.hidden=true;panel.innerHTML='<div class="opportunity-head"><div><p class="eyebrow">INTELIGÊNCIA TERRITORIAL</p><h3>Oportunidades de expansão</h3></div><button type="button" class="opportunity-close">Fechar</button></div><p class="coverage">A análise usa os dados eleitorais carregados. População e eleitorado oficial serão preenchidos quando as bases IBGE/TSE forem adicionadas.</p><div class="opportunity-summary"></div><div class="opportunity-list"></div>';territory.appendChild(panel);
  button.onclick=()=>{const c=window.__exportCandidate,rows=window.__exportRows||[];if(!c)return;const years=c.years.map(String),groups={};rows.forEach(x=>{const key=x.municipality;groups[key]??={municipality:key,region:x.region,votes:0,difference:0,places:0};groups[key].votes+=x.votes[years[1]]||0;groups[key].difference+=(x.difference||0);groups[key].places++});const ranked=Object.values(groups).sort((a,b)=>a.votes-b.votes),growth=ranked.filter(x=>x.difference>0).length,reduction=ranked.filter(x=>x.difference<0).length,stable=ranked.filter(x=>x.difference===0).length,top=[...ranked].sort((a,b)=>b.votes-a.votes)[0],zero=ranked.filter(x=>x.votes===0).length;panel.querySelector('.opportunity-summary').innerHTML=`<div class="evolution-grid"><span><b>${growth.toLocaleString('pt-BR')}</b><small>Crescimento</small></span><span><b>${reduction.toLocaleString('pt-BR')}</b><small>Redução</small></span><span><b>${stable.toLocaleString('pt-BR')}</b><small>Estagnados</small></span><span><b>${top?top.votes.toLocaleString('pt-BR'):0}</b><small>Mais votos em ${years[1]}</small></span></div><p><strong>${zero.toLocaleString('pt-BR')}</strong> municípios sem votos · <strong>${ranked.length.toLocaleString('pt-BR')}</strong> avaliados</p>`;panel.querySelector('.opportunity-list').innerHTML=ranked.slice(0,12).map((x,i)=>`<div class="opportunity-row"><b>${i+1}</b><span><strong>${x.municipality}</strong><small>${x.region} · ${x.places} zonas · ${x.difference>0?'crescimento':x.difference<0?'redução':'estagnação'}</small></span><em>${x.votes.toLocaleString('pt-BR')} em ${years[1]}<br><small>variação: ${x.difference.toLocaleString('pt-BR')}</small></em></div>`).join('');panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'nearest'})};panel.querySelector('.opportunity-close').onclick=()=>{panel.hidden=true};
}());
(function improveMobileMenu(){
  if(typeof document==='undefined')return;
  const aside=document.querySelector('aside'),menu=document.querySelector('#menuButton');if(!aside||!menu)return;
  const close=document.createElement('button');close.type='button';close.className='menu-close';close.setAttribute('aria-label','Fechar menu');close.textContent='×';aside.insertBefore(close,aside.firstChild);
  const closeMenu=()=>{document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false');};
  close.onclick=closeMenu;aside.querySelectorAll('nav a').forEach(link=>link.addEventListener('click',closeMenu));
  document.addEventListener('click',event=>{if(document.body.classList.contains('menu-open')&&!aside.contains(event.target)&&event.target!==menu)closeMenu()});
}());
(function addSessionLogout(){
  if(typeof document==='undefined')return;
  const header=document.querySelector('header');if(!header||document.querySelector('#logoutButton'))return;
  const button=document.createElement('button');button.id='logoutButton';button.type='button';button.className='logout-action';button.textContent='Logout';button.setAttribute('aria-label','Sair do painel');header.appendChild(button);
  button.onclick=()=>{sessionStorage.removeItem('candidate_access');window.location.reload()};
}());
(function lockViewport(){
  if(typeof document==='undefined')return;
  let meta=document.querySelector('meta[name="viewport"]');if(!meta){meta=document.createElement('meta');meta.name='viewport';document.head.appendChild(meta)}meta.content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover';
}());
